# Generated by Django 3.1.2 on 2020-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
