# Generated by Django 3.1.2 on 2020-10-23 18:51

import diet.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='objectives',
            field=models.OneToOneField(blank=True, default=diet.models.default_new_objective, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.objectives'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
