# Generated by Django 3.1.2 on 2020-10-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_auto_20201023_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('none', 'None')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
