# Generated by Django 3.1.2 on 2020-10-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_auto_20201023_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
