# Generated by Django 3.1.2 on 2020-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_auto_20201023_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.FloatField(default=1),
        ),
    ]
