# Generated by Django 3.1.2 on 2020-10-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_auto_20201023_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('none', 'None')], max_length=200, null=True),
        ),
    ]
