# Generated by Django 3.1.2 on 2020-10-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_product_name'),
        ('diet', '0006_recipe_servings'),
    ]

    operations = [
    ]
